name: Desplegar estáticos

on:
  push:
    branches: ["prod-ec2"]
  pull_request:
    branches: ["prod-ec2"]


jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copiar estáticos
        run: bash ./copy.sh
